import type { Vocabulary } from '@/types/Vocabulary';

export const vocabularies: Vocabulary[] = [
  {
    sortOrder: 154,
    content: 'responsibility',
    explain: '责任',
    more: 'responsible, responsibilities',
  },
  { sortOrder: 155, content: 'right', explain: '正确的、右边的、权利', more: 'rights' },
  {
    sortOrder: 156,
    content: 'serious',
    explain: '严肃认真的、严重的',
    more: 'seriously, seriousness',
  },
  { sortOrder: 157, content: 'share', explain: '分享', more: 'shared, sharing' },
  { sortOrder: 158, content: 'stop', explain: '停止、阻止', more: 'stopped, stopping' },
  {
    sortOrder: 159,
    content: 'struggle',
    explain: '斗争、挣扎、奋斗',
    more: 'struggles, struggled, struggling',
  },
  {
    sortOrder: 160,
    content: 'teach',
    explain: '教',
    more: 'teaches, taught, teaching, teacher, teachers',
  },
  { sortOrder: 161, content: 'through', explain: '通过、穿过', more: '' },
  {
    sortOrder: 162,
    content: 'treat',
    explain: '对待、款待、治疗',
    more: 'treated, treating, treatment',
  },
  {
    sortOrder: 163,
    content: 'appear',
    explain: '出现',
    more: 'appeared, appears, appearance, appearances, disappear',
  },
  {
    sortOrder: 164,
    content: 'drop',
    explain: '掉落、下降、水滴',
    more: 'dropped, dropping, dropout',
  },
  { sortOrder: 165, content: 'energy', explain: '精力', more: 'energetic' },
  { sortOrder: 166, content: 'grateful', explain: '感激的', more: 'gratefully, gratitude' },
  { sortOrder: 167, content: 'honest', explain: '诚实的', more: 'honestly, honesty, dishonesty' },
  { sortOrder: 168, content: 'love', explain: '爱', more: 'lovely, loved, loving, lovingly' },
  { sortOrder: 169, content: 'meet', explain: '遇见、会面', more: 'met, meeting, meetings' },
  { sortOrder: 170, content: 'mind', explain: '思维、想法、介意', more: 'minds, minded, minding' },
  {
    sortOrder: 171,
    content: 'nature',
    explain: '自然、本性',
    more: 'natural, naturally, natures',
  },
  { sortOrder: 172, content: 'pain', explain: '痛苦', more: 'painful, painfully, pains, pained' },
  { sortOrder: 173, content: 'point', explain: '点、重点、指', more: 'pointed, points, pointing' },
  {
    sortOrder: 174,
    content: 'practical',
    explain: '实际的、实用的',
    more: 'practice, practices, practicing, practiced, practised, practically',
  },
  { sortOrder: 175, content: 'read', explain: '读', more: 'reading, reads, reread' },
  {
    sortOrder: 176,
    content: 'receive',
    explain: '收到',
    more: 'received, receiving, receiver, reception, receptionist, receptionists',
  },
  { sortOrder: 177, content: 'talk', explain: '说', more: 'talked, talking, talkative, talkers' },
  {
    sortOrder: 178,
    content: 'training',
    explain: '训练',
    more: 'train, trains, trained, trainer',
  },
  {
    sortOrder: 179,
    content: 'understand',
    explain: '理解',
    more: 'understanding, understood, understandingly, misunderstanding',
  },
  {
    sortOrder: 180,
    content: 'advice',
    explain: '建议',
    more: 'advise, advised, adviser, advisor',
  },
  {
    sortOrder: 181,
    content: 'appreciate',
    explain: '欣赏、感激',
    more: 'appreciated, appreciation',
  },
  {
    sortOrder: 182,
    content: 'arrange',
    explain: '安排',
    more: 'arranged, arranging, arrangement',
  },
];
