/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainVocabularyIndexRouteImport } from './routes/_main/vocabulary/index'
import { Route as MainEchoIndexRouteImport } from './routes/_main/echo/index'
import { Route as MainVocabularySummaryRouteImport } from './routes/_main/vocabulary/summary'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainVocabularyIndexRoute = MainVocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => MainRoute,
} as any)
const MainEchoIndexRoute = MainEchoIndexRouteImport.update({
  id: '/echo/',
  path: '/echo/',
  getParentRoute: () => MainRoute,
} as any)
const MainVocabularySummaryRoute = MainVocabularySummaryRouteImport.update({
  id: '/vocabulary/summary',
  path: '/vocabulary/summary',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vocabulary/summary': typeof MainVocabularySummaryRoute
  '/echo/': typeof MainEchoIndexRoute
  '/vocabulary/': typeof MainVocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vocabulary/summary': typeof MainVocabularySummaryRoute
  '/echo': typeof MainEchoIndexRoute
  '/vocabulary': typeof MainVocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/about': typeof AboutRoute
  '/_main/vocabulary/summary': typeof MainVocabularySummaryRoute
  '/_main/echo/': typeof MainEchoIndexRoute
  '/_main/vocabulary/': typeof MainVocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/vocabulary/summary' | '/echo/' | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/vocabulary/summary' | '/echo' | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/about'
    | '/_main/vocabulary/summary'
    | '/_main/echo/'
    | '/_main/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/vocabulary/': {
      id: '/_main/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof MainVocabularyIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/echo/': {
      id: '/_main/echo/'
      path: '/echo'
      fullPath: '/echo/'
      preLoaderRoute: typeof MainEchoIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/vocabulary/summary': {
      id: '/_main/vocabulary/summary'
      path: '/vocabulary/summary'
      fullPath: '/vocabulary/summary'
      preLoaderRoute: typeof MainVocabularySummaryRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainVocabularySummaryRoute: typeof MainVocabularySummaryRoute
  MainEchoIndexRoute: typeof MainEchoIndexRoute
  MainVocabularyIndexRoute: typeof MainVocabularyIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainVocabularySummaryRoute: MainVocabularySummaryRoute,
  MainEchoIndexRoute: MainEchoIndexRoute,
  MainVocabularyIndexRoute: MainVocabularyIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
